#!/usr/bin/env python3
"""
DISC-8 Phase 1, Item 2: VP Single-Threshold Revisit
=====================================================
Prove that single-threshold VP running has no periodic
structure under any smooth change of variables.
"""

print("=" * 70)
print("DISC-8 PHASE 1, ITEM 2: VP SINGLE-THRESHOLD CLOSURE")
print("=" * 70)
print()

print("THEOREM: The VP running between adjacent thresholds has no")
print("periodic structure under any smooth change of variables.")
print()
print("PROOF:")
print()
print("  Between two adjacent mass thresholds m_f and m_{f+1},")
print("  the coupling runs as:")
print()
print("    alpha^{-1}(mu) = alpha^{-1}(m_f) + (b/2pi) * ln(mu/m_f)")
print()
print("  Define kappa = ln(mu/m_f). Then:")
print()
print("    alpha^{-1}(kappa) = alpha^{-1}(0) + c * kappa")
print()
print("  where c = b/(2pi) is a positive constant (for asymptotic freedom).")
print()
print("  This is a LINEAR function of kappa: f(kappa) = a + c*kappa.")
print()
print("  Claim: No smooth bijection g: R -> R makes f(g(x)) periodic.")
print()
print("  Proof: Suppose f(g(x)) = a + c*g(x) is periodic with period P.")
print("  Then f(g(x+P)) = f(g(x)) for all x.")
print("  So a + c*g(x+P) = a + c*g(x).")
print("  So g(x+P) = g(x) for all x.")
print("  But g is a bijection (invertible), and a periodic function")
print("  is not injective (g(0) = g(P) = g(2P) = ...).")
print("  Contradiction. QED.")
print()
print("  The argument extends: ANY monotonic function composed with")
print("  ANY bijection remains non-periodic, because periodicity")
print("  requires the function to return to a previous value,")
print("  which a monotonic-composed-with-bijection cannot do.")
print()
print("RESULT: The Q5 null from DISC-7 is CLOSED DEFINITIVELY.")
print("  Not just for the full VP running (unequal thresholds),")
print("  but for each single-threshold segment individually.")
print("  The VP running is structurally monotonic at every scale.")
print("  No change of variables can introduce periodicity.")
print()
print("  Subgroup B (monotonic accumulation) is IRREDUCIBLY")
print("  distinct from Subgroup A (phase-periodic).")
print("  The separation is topological: monotonic vs periodic")
print("  is a property preserved under all smooth coordinate changes.")
